<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <NoWarn>$(NoWarn);CA1416;CS8632;8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Genesis.Shared\Genesis.Shared.csproj" />
    <ProjectReference Include="..\Genesis.Rendering.Abstractions\Genesis.Rendering.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Core" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Direct3D12" Version="2.23.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross" Version="2.23.0" />
    <PackageReference Include="Silk.NET.SPIRV.Cross.Native" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageReference Include="StbImageSharp" Version="2.27.14" />
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
    <PackageReference Include="Microsoft.Direct3D.DXC" Version="1.9.2607.13" PrivateAssets="all" ExcludeAssets="build;buildTransitive" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shaders\Genesis.hlsli" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
