using System.Collections.Generic;

namespace Genesis.Shared.Scripting
{
    /// <summary>Full legacy PGSL command catalogue (~415 commands) sourced from
    /// Documentation/PGSLCommands.md. This is the complete reference list of every
    /// PGSL command that has ever existed in the language, used to populate the PGSL
    /// Commands Browser in full. <see cref="PgslCommandRegistry.GetFullCatalog"/> merges
    /// this seed with the live <see cref="PgslCommandAttribute"/>-tagged catalog to
    /// automatically compute which commands are actually implemented.</summary>
    public static class PgslCommandCatalogSeed
    {
        public static readonly PgslSeedEntry[] All =
        {
            new PgslSeedEntry("AngleBetweenPoints3D", "AngleBetweenPoints3D(x1, y1, z1, x2, y2, z2) → float", "PGSL.AngleBetweenPoints3D", "Yaw angle in degrees from first point toward second on XZ plane", "3D Math"),
            new PgslSeedEntry("AngleBetweenVectors3D", "AngleBetweenVectors3D(x1, y1, z1, x2, y2, z2) → float", "PGSL.AngleBetweenVectors3D", "Angle in degrees between two direction vectors", "3D Math"),
            new PgslSeedEntry("DistanceBetweenPoints3D", "DistanceBetweenPoints3D(x1, y1, z1, x2, y2, z2) → float", "PGSL.DistanceBetweenPoints3D", "3D Euclidean distance", "3D Math"),
            new PgslSeedEntry("GetFacingDirection", "GetFacingDirection(objectName) → float", "PGSL.GetFacingDirection", "Returns the Direction angle of the named object", "3D Math"),
            new PgslSeedEntry("GetForwardDirection", "GetForwardDirection(facingAngle) → any", "PGSL.GetForwardDirection", "Returns (dx,dy,dz) unit vector; view yaw 0° = look +Z", "3D Math"),
            new PgslSeedEntry("GetMyFacingDirection", "GetMyFacingDirection() → float", "PGSL.GetMyFacingDirection", "Returns this object's own Direction angle", "3D Math"),
            new PgslSeedEntry("GetViewForwardDirection", "GetViewForwardDirection(view) → any", "PGSL.GetViewForwardDirection", "View look direction unit vector (dx,dy,dz)", "3D Math"),
            new PgslSeedEntry("MoveForward3D", "MoveForward3D(distance, pitchDeg)", "PGSL.MoveForward3D", "Move forward using Direction (yaw) and pitch on X/Y/Z", "3D Math"),
            new PgslSeedEntry("PointDirection3D", "PointDirection3D(x1, y1, z1, x2, y2, z2) → float", "PGSL.PointDirection3D", "Yaw angle in degrees from first point toward second on XZ plane", "3D Math"),

            new PgslSeedEntry("AnimationBlend", "AnimationBlend(animName, blendDuration)", "PGSL.AnimationBlend", "Crossfade to a new animation over blendDuration seconds", "Animation"),
            new PgslSeedEntry("AnimationPlay", "AnimationPlay(modelName, animName, speed)", "PGSL.AnimationPlay", "Start playing a named animation on a model", "Animation"),
            new PgslSeedEntry("AnimationStop", "AnimationStop()", "PGSL.AnimationStop", "Stop animation and return to bind pose", "Animation"),
            new PgslSeedEntry("ArrayLength", "ArrayLength(arr) → int", "PGSL.ArrayLength", "Get number of elements", "Arrays"),
            new PgslSeedEntry("ArrayPop", "ArrayPop(arr) → any", "PGSL.ArrayPop", "Remove from end and return", "Arrays"),
            new PgslSeedEntry("ArrayPush", "ArrayPush(arr, val)", "PGSL.ArrayPush", "Add to end", "Arrays"),
            new PgslSeedEntry("AudioMasterVolume", "AudioMasterVolume(vol)", "PGSL.AudioMasterVolume", "Set master volume 0-1", "Audio"),
            new PgslSeedEntry("AudioPlay", "AudioPlay(sound, loops) → int", "PGSL.AudioPlay", "Play sound; loops 0=use .audio.json loop, -1=force loop, N=play N times", "Audio"),
            new PgslSeedEntry("AudioStop", "AudioStop(id)", "PGSL.AudioStop", "Stop sound voice", "Audio"),
            new PgslSeedEntry("DsListAdd", "DsListAdd(id, value)", "PGSL.DsListAdd", "Append value to list", "Data Structures"),
            new PgslSeedEntry("DsListClear", "DsListClear(id)", "PGSL.DsListClear", "Clear all elements in a list", "Data Structures"),
            new PgslSeedEntry("DsListCreate", "DsListCreate() → float", "PGSL.DsListCreate", "Create a new list and return its id", "Data Structures"),
            new PgslSeedEntry("DsListDelete", "DsListDelete(id, index)", "PGSL.DsListDelete", "Remove list element", "Data Structures"),
            new PgslSeedEntry("DsListDestroy", "DsListDestroy(id)", "PGSL.DsListDestroy", "Destroy a list", "Data Structures"),
            new PgslSeedEntry("DsListFind", "DsListFind(id, index) → any", "PGSL.DsListFind", "Get list element", "Data Structures"),
            new PgslSeedEntry("DsListSet", "DsListSet(id, index, value)", "PGSL.DsListSet", "Set list element", "Data Structures"),
            new PgslSeedEntry("DsListSize", "DsListSize(id) → float", "PGSL.DsListSize", "Get list size", "Data Structures"),
            new PgslSeedEntry("PgFree", "PgFree(handle)", "PGSL.PgFree", "Free a PG data structure from memory", "Data Structures"),
            new PgslSeedEntry("ColorGetBlue", "ColorGetBlue(c) → int", "PGSL.ColorGetBlue", "Get blue component of color", "Drawing 2D"),
            new PgslSeedEntry("ColorGetGreen", "ColorGetGreen(c) → int", "PGSL.ColorGetGreen", "Get green component of color", "Drawing 2D"),
            new PgslSeedEntry("ColorGetHue", "ColorGetHue(c) → float", "PGSL.ColorGetHue", "Get hue of color", "Drawing 2D"),
            new PgslSeedEntry("ColorGetRed", "ColorGetRed(c) → int", "PGSL.ColorGetRed", "Get red component of color", "Drawing 2D"),
            new PgslSeedEntry("ColorGetSaturation", "ColorGetSaturation(c) → float", "PGSL.ColorGetSaturation", "Get saturation of color", "Drawing 2D"),
            new PgslSeedEntry("ColorGetValue", "ColorGetValue(c) → float", "PGSL.ColorGetValue", "Get brightness/value of color", "Drawing 2D"),
            new PgslSeedEntry("ColourBlack", "ColourBlack → color", "PGSL.ColourBlack", "Get black colour", "Drawing 2D"),
            new PgslSeedEntry("ColourBlue", "ColourBlue → color", "PGSL.ColourBlue", "Get blue colour", "Drawing 2D"),
            new PgslSeedEntry("ColourCyan", "ColourCyan → color", "PGSL.ColourCyan", "Get cyan colour", "Drawing 2D"),
            new PgslSeedEntry("ColourGray", "ColourGray → color", "PGSL.ColourGray", "Get gray colour", "Drawing 2D"),
            new PgslSeedEntry("ColourGreen", "ColourGreen → color", "PGSL.ColourGreen", "Get green colour", "Drawing 2D"),
            new PgslSeedEntry("ColourOrange", "ColourOrange → color", "PGSL.ColourOrange", "Get orange colour", "Drawing 2D"),
            new PgslSeedEntry("ColourPurple", "ColourPurple → color", "PGSL.ColourPurple", "Get purple colour", "Drawing 2D"),
            new PgslSeedEntry("ColourRandom", "ColourRandom → color", "PGSL.ColourRandom", "Get a random colour", "Drawing 2D"),
            new PgslSeedEntry("ColourRed", "ColourRed → color", "PGSL.ColourRed", "Get red colour", "Drawing 2D"),
            new PgslSeedEntry("ColourWhite", "ColourWhite → color", "PGSL.ColourWhite", "Get white colour", "Drawing 2D"),
            new PgslSeedEntry("ColourYellow", "ColourYellow → color", "PGSL.ColourYellow", "Get yellow colour", "Drawing 2D"),
            new PgslSeedEntry("DrawCircle", "DrawCircle(x, y, r, filled)", "PGSL.DrawCircle", "Draw circle", "Drawing 2D"),
            new PgslSeedEntry("DrawClear", "DrawClear(color)", "PGSL.DrawClear", "Clear viewport", "Drawing 2D"),
            new PgslSeedEntry("DrawLine", "DrawLine(x1, y1, x2, y2)", "PGSL.DrawLine", "Draw line", "Drawing 2D"),
            new PgslSeedEntry("DrawPoint", "DrawPoint(x, y)", "PGSL.DrawPoint", "Draw single pixel", "Drawing 2D"),
            new PgslSeedEntry("DrawRectangle", "DrawRectangle(x1, y1, x2, y2, filled)", "PGSL.DrawRectangle", "Draw rectangle", "Drawing 2D"),
            new PgslSeedEntry("DrawSelf", "DrawSelf()", "PGSL.DrawSelf", "Draw instance using its own sprite properties", "Drawing 2D"),
            new PgslSeedEntry("DrawSetAlpha", "DrawSetAlpha(a)", "PGSL.DrawSetAlpha", "Set drawing transparency", "Drawing 2D"),
            new PgslSeedEntry("DrawSetColor", "DrawSetColor(color)", "PGSL.DrawSetColor", "Set drawing color", "Drawing 2D"),
            new PgslSeedEntry("DrawSetFont", "DrawSetFont(name, size)", "PGSL.DrawSetFont", "Set drawing font", "Drawing 2D"),
            new PgslSeedEntry("DrawSprite", "DrawSprite(spr, frame, x, y)", "PGSL.DrawSprite", "Draw sprite resource", "Drawing 2D"),
            new PgslSeedEntry("DrawSpriteExt", "DrawSpriteExt(spr, frame, x, y, xscale, yscale, rot, col, alpha)", "PGSL.DrawSpriteExt", "Draw sprite with extended properties", "Drawing 2D"),
            new PgslSeedEntry("DrawText", "DrawText(x, y, text)", "PGSL.DrawText", "Draw text", "Drawing 2D"),
            new PgslSeedEntry("MakeColorHsv", "MakeColorHsv(h, s, v) → color", "PGSL.MakeColorHsv", "Create color from HSV components", "Drawing 2D"),
            new PgslSeedEntry("MakeColorRgb", "MakeColorRgb(r, g, b) → color", "PGSL.MakeColorRgb", "Create color from RGB", "Drawing 2D"),
            new PgslSeedEntry("MergeColor", "MergeColor(a, b, t) → color", "PGSL.MergeColor", "Blend two colors", "Drawing 2D"),
            new PgslSeedEntry("DrawCube3D", "DrawCube3D(xfrom, yfrom, zfrom, xto, yto, zto, color, xrot, yrot, zrot, alpha)", "PGSL.DrawCube3D", "Draw a solid 3D box", "Drawing 3D"),
            new PgslSeedEntry("DrawModel", "DrawModel(modelName, animName, speed, x, y, z)", "PGSL.DrawModel", "Draw a 3D model at a world position", "Drawing 3D"),
            new PgslSeedEntry("DrawModelTransform3D", "DrawModelTransform3D(modelName, x, y, z, sx, sy, sz, xrot, yrot, zrot)", "PGSL.DrawModelTransform3D", "Draw a model resource with a complete transform", "Drawing 3D"),
            new PgslSeedEntry("DrawModelShader3D", "DrawModelShader3D(modelName, shaderName, x, y, z, sx, sy, sz, xrot, yrot, zrot)", "PGSL.DrawModelShader3D", "Draw a model resource through an authored mesh shader", "Drawing 3D"),
            new PgslSeedEntry("DrawPointLight3D", "DrawPointLight3D(x, y, z, radius, intensity, r, g, b)", "PGSL.DrawPointLight3D", "Add an omnidirectional light during the 3D draw pass", "Drawing 3D"),
            new PgslSeedEntry("DrawModelSelf", "DrawModelSelf(modelName, animName, speed)", "PGSL.DrawModelSelf", "Draw a 3D model at this instance position", "Drawing 3D"),
            new PgslSeedEntry("DrawSphere3D", "DrawSphere3D(xfrom, yfrom, zfrom, xto, yto, zto, color, xrot, yrot, zrot, alpha)", "PGSL.DrawSphere3D", "Draw a solid 3D sphere (box bounds)", "Drawing 3D"),
            new PgslSeedEntry("DrawTriangle3D", "DrawTriangle3D(xfrom, yfrom, zfrom, xto, yto, zto, color, xrot, yrot, zrot, alpha)", "PGSL.DrawTriangle3D", "Draw a solid 3D triangle (corner bounds)", "Drawing 3D"),
            new PgslSeedEntry("TerrainGetHeight", "TerrainGetHeight(x, z) → float", "PGSL.TerrainGetHeight", "Get terrain height at world position", "Drawing 3D"),
            new PgslSeedEntry("Engine.AddLight2D", "Engine.AddLight2D(x, y, radius, r, g, b, intensity)", "PGSL.AddLight2D", "Add a 2D point light (tiled deferred sprite lighting)", "Engine Commands"),
            new PgslSeedEntry("Engine.ApplySettings", "Engine.ApplySettings()", "PGSL.ApplyEngineSettings", "Apply pending engine settings immediately", "Engine Commands"),
            new PgslSeedEntry("Engine.ClearLights2D", "Engine.ClearLights2D()", "PGSL.ClearLights2D", "Remove all runtime 2D point lights", "Engine Commands"),
            new PgslSeedEntry("Engine.EnableFirstPersonCamera", "Engine.EnableFirstPersonCamera(enabled)", "PGSL.EnableFirstPersonCamera", "No-op: 3D play always uses view fly camera", "Engine Commands"),
            new PgslSeedEntry("Engine.Get3DTextureAtlas", "Engine.Get3DTextureAtlas() → bool", "PGSL.Get3DTextureAtlas", "Check if 3D texture atlasing is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetAtlasMaxSize", "Engine.GetAtlasMaxSize() → float", "PGSL.GetTextureAtlasMaxSize", "Get maximum texture atlas size", "Engine Commands"),
            new PgslSeedEntry("Engine.GetBackfaceCulling", "Engine.GetBackfaceCulling() → bool", "PGSL.GetBackfaceCulling", "Check if backface culling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetDeferredLighting2D", "Engine.GetDeferredLighting2D() → bool", "PGSL.GetDeferredLighting2D", "Check if 2D deferred tiled lighting is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetDeferredLighting3D", "Engine.GetDeferredLighting3D() → bool", "PGSL.GetDeferredLighting3D", "Check if 3D deferred tiled lighting is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetFaceCulling", "Engine.GetFaceCulling() → float", "PGSL.GetFaceCulling", "Get face culling mode: 0=Back, 1=Front, 2=None", "Engine Commands"),
            new PgslSeedEntry("Engine.GetFirstPersonCamera", "Engine.GetFirstPersonCamera() → float", "PGSL.GetFirstPersonCamera", "Returns 1 (3D play uses view fly by default)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetFogEnabled", "Engine.GetFogEnabled() → bool", "PGSL.GetFogEnabled", "Check if fog is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetFrustumCulling", "Engine.GetFrustumCulling() → bool", "PGSL.GetFrustumCulling", "Check if frustum culling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetGlobalLighting", "Engine.GetGlobalLighting() → bool", "PGSL.GetGlobalLighting", "Check if global lighting is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetGpuCulling", "Engine.GetGpuCulling() → bool", "PGSL.GetGpuCulling", "Check if GPU compute instance culling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetLODFar", "Engine.GetLODFar() → float", "PGSL.GetLODFar", "Get LOD far cull distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetLODMid", "Engine.GetLODMid() → float", "PGSL.GetLODMid", "Get LOD mid distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetLODNear", "Engine.GetLODNear() → float", "PGSL.GetLODNear", "Get LOD near distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetLodScaling", "Engine.GetLodScaling() → bool", "PGSL.GetLodScaling", "Check if LOD scaling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetLODScaling", "Engine.GetLODScaling() → bool", "PGSL.GetLodScaling", "Check if LOD scaling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetOcclusionCulling", "Engine.GetOcclusionCulling() → bool", "PGSL.GetOcclusionCulling", "Check if occlusion culling is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetRenderMode", "Engine.GetRenderMode() → string", "PGSL.GetRenderMode", "Get current render mode override (Auto, 2D, 3D)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetTextureAllocSize", "Engine.GetTextureAllocSize() → float", "PGSL.GetTextureAllocSize", "Get default texture allocation size in pixels", "Engine Commands"),
            new PgslSeedEntry("Engine.GetTextureAtlas", "Engine.GetTextureAtlas() → bool", "PGSL.Get3DTextureAtlas", "Check if 3D texture atlasing is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetTextureAtlasMaxSize", "Engine.GetTextureAtlasMaxSize() → float", "PGSL.GetTextureAtlasMaxSize", "Get maximum texture atlas size", "Engine Commands"),
            new PgslSeedEntry("Engine.GetTextureMaxSize", "Engine.GetTextureMaxSize() → float", "PGSL.GetTextureMaxSize", "Get maximum texture size", "Engine Commands"),
            new PgslSeedEntry("Engine.GetVsync", "Engine.GetVsync() → bool", "PGSL.GetVsync", "Check if vertical sync (VSync) is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetVSync", "Engine.GetVSync() → bool", "PGSL.GetVsync", "Check if vertical sync (VSync) is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.GetWindingOrder", "Engine.GetWindingOrder() → bool", "PGSL.GetWindingOrder", "Check if winding order is CCW (counter-clockwise)", "Engine Commands"),
            new PgslSeedEntry("Engine.GetZPrepass3D", "Engine.GetZPrepass3D() → bool", "PGSL.GetZPrepass3D", "Check if 3D Z-prepass is enabled", "Engine Commands"),
            new PgslSeedEntry("Engine.Set3DTextureAtlas", "Engine.Set3DTextureAtlas(enabled)", "PGSL.Set3DTextureAtlas", "Enable or disable 3D texture atlasing", "Engine Commands"),
            new PgslSeedEntry("Engine.SetAmbientLight", "Engine.SetAmbientLight(r, g, b)", "PGSL.SetAmbientLight", "Set ambient light color", "Engine Commands"),
            new PgslSeedEntry("Engine.SetAtlasMaxSize", "Engine.SetAtlasMaxSize(size)", "PGSL.SetTextureAtlasMaxSize", "Set maximum texture atlas size", "Engine Commands"),
            new PgslSeedEntry("Engine.SetBackfaceCulling", "Engine.SetBackfaceCulling(enabled)", "PGSL.SetBackfaceCulling", "Enable or disable backface culling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetCameraFov", "Engine.SetCameraFov(degrees)", "PGSL.SetCameraFov", "Override play camera field of view", "Engine Commands"),
            new PgslSeedEntry("Engine.SetCameraNearPlane", "Engine.SetCameraNearPlane(distance)", "PGSL.SetCameraNearPlane", "Override play camera near clipping plane", "Engine Commands"),
            new PgslSeedEntry("Engine.SetCameraFarPlane", "Engine.SetCameraFarPlane(distance)", "PGSL.SetCameraFarPlane", "Override play camera far clipping plane", "Engine Commands"),
            new PgslSeedEntry("Engine.SetCameraPosition", "Engine.SetCameraPosition(x, y, z)", "PGSL.SetCameraPosition", "Override play camera position", "Engine Commands"),
            new PgslSeedEntry("Engine.SetCameraTarget", "Engine.SetCameraTarget(x, y, z)", "PGSL.SetCameraTarget", "Override play camera look-at target", "Engine Commands"),
            new PgslSeedEntry("Engine.SetDeferredLighting2D", "Engine.SetDeferredLighting2D(enabled)", "PGSL.SetDeferredLighting2D", "Enable tiled light-map composite for GPU 2D sprites", "Engine Commands"),
            new PgslSeedEntry("Engine.SetDeferredLighting3D", "Engine.SetDeferredLighting3D(enabled)", "PGSL.SetDeferredLighting3D", "Enable G-buffer + tiled deferred lighting for 3D scenes", "Engine Commands"),
            new PgslSeedEntry("Engine.SetFaceCulling", "Engine.SetFaceCulling(mode)", "PGSL.SetFaceCulling", "Set face culling mode: 0=Back, 1=Front, 2=None", "Engine Commands"),
            new PgslSeedEntry("Engine.SetFog", "Engine.SetFog(enabled, r, g, b, start, end, alpha=1)", "PGSL.SetFog", "Configure fog: End-Start is thickness; 2D uses authored Z/layer depth, 3D uses camera distance; alpha sets maximum opacity", "Engine Commands"),
            new PgslSeedEntry("Engine.SetFrustumCulling", "Engine.SetFrustumCulling(enabled)", "PGSL.SetFrustumCulling", "Enable or disable frustum culling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetGlobalLightColor", "Engine.SetGlobalLightColor(r, g, b)", "PGSL.SetGlobalLightColor", "Set global light color", "Engine Commands"),
            new PgslSeedEntry("Engine.SetGlobalLightDirection", "Engine.SetGlobalLightDirection(x, y, z)", "PGSL.SetGlobalLightDirection", "Set global light direction", "Engine Commands"),
            new PgslSeedEntry("Engine.SetGlobalLightDirection2D", "Engine.SetGlobalLightDirection2D(x, y)", "PGSL.SetGlobalLightDirection2D", "Set 2D directional light vector (screen/world XY)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetGlobalLighting", "Engine.SetGlobalLighting(enabled)", "PGSL.SetGlobalLighting", "Enable or disable global lighting", "Engine Commands"),
            new PgslSeedEntry("Engine.SetGpuCulling", "Engine.SetGpuCulling(enabled)", "PGSL.SetGpuCulling", "Enable or disable GPU compute instance culling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetLODFar", "Engine.SetLODFar(distance)", "PGSL.SetLODFar", "Set LOD far cull distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetLODMid", "Engine.SetLODMid(distance)", "PGSL.SetLODMid", "Set LOD mid distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetLODNear", "Engine.SetLODNear(distance)", "PGSL.SetLODNear", "Set LOD near distance (meters)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetLodScaling", "Engine.SetLodScaling(enabled)", "PGSL.SetLodScaling", "Enable or disable LOD scaling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetLODScaling", "Engine.SetLODScaling(enabled)", "PGSL.SetLodScaling", "Enable or disable LOD scaling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetOcclusionCulling", "Engine.SetOcclusionCulling(enabled)", "PGSL.SetOcclusionCulling", "Enable or disable occlusion culling", "Engine Commands"),
            new PgslSeedEntry("Engine.SetRenderMode", "Engine.SetRenderMode(mode)", "PGSL.SetRenderMode", "Set render mode: Auto, 2D, or 3D", "Engine Commands"),
            new PgslSeedEntry("Engine.SetTextureAllocSize", "Engine.SetTextureAllocSize(size)", "PGSL.SetTextureAllocSize", "Set default texture allocation size in pixels (default 256)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetTextureAtlas", "Engine.SetTextureAtlas(enabled)", "PGSL.Set3DTextureAtlas", "Enable or disable 3D texture atlasing", "Engine Commands"),
            new PgslSeedEntry("Engine.SetTextureAtlasMaxSize", "Engine.SetTextureAtlasMaxSize(size)", "PGSL.SetTextureAtlasMaxSize", "Set maximum texture atlas size", "Engine Commands"),
            new PgslSeedEntry("Engine.SetTextureMaxSize", "Engine.SetTextureMaxSize(size)", "PGSL.SetTextureMaxSize", "Set maximum texture size (0 = unclamped)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetVsync", "Engine.SetVsync(enabled)", "PGSL.SetVsync", "Enable or disable vertical sync (VSync)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetVSync", "Engine.SetVSync(enabled)", "PGSL.SetVsync", "Enable or disable vertical sync (VSync)", "Engine Commands"),
            new PgslSeedEntry("Engine.SetWindingOrder", "Engine.SetWindingOrder(ccw)", "PGSL.SetWindingOrder", "Set winding order: true=CCW (counter-clockwise), false=CW", "Engine Commands"),
            new PgslSeedEntry("Engine.SetZPrepass3D", "Engine.SetZPrepass3D(enabled)", "PGSL.SetZPrepass3D", "Enable 3D depth prepass (auto-on with deferred lighting)", "Engine Commands"),
            new PgslSeedEntry("DeltaTime", "DeltaTime → float", "PGSL.DeltaTime", "Time since last frame", "Engine Variables"),
            new PgslSeedEntry("Fps", "Fps → float", "PGSL.Fps", "Current frames per second", "Engine Variables"),
            new PgslSeedEntry("MouseRawX", "MouseRawX → float", "PGSL.MouseRawX", "Raw Mouse X in screen coordinates", "Engine Variables"),
            new PgslSeedEntry("MouseRawY", "MouseRawY → float", "PGSL.MouseRawY", "Raw Mouse Y in screen coordinates", "Engine Variables"),
            new PgslSeedEntry("MouseX", "MouseX → float", "PGSL.MouseX", "Mouse X in world coordinates", "Engine Variables"),
            new PgslSeedEntry("MouseY", "MouseY → float", "PGSL.MouseY", "Mouse Y in world coordinates", "Engine Variables"),
            new PgslSeedEntry("RoomHeight", "RoomHeight → float", "PGSL.RoomHeight", "Current room height in pixels", "Engine Variables"),
            new PgslSeedEntry("RoomSpeed", "RoomSpeed → int", "PGSL.RoomSpeed", "Target frames per second", "Engine Variables"),
            new PgslSeedEntry("RoomWidth", "RoomWidth → float", "PGSL.RoomWidth", "Current room width in pixels", "Engine Variables"),
            new PgslSeedEntry("FileReadINI", "FileReadINI(section, key, defaultVal) → string", "PGSL.FileReadINI", "Read value from INI file", "File I/O"),
            new PgslSeedEntry("FileWriteINI", "FileWriteINI(path, section, key, value)", "PGSL.FileWriteINI", "Write value to INI file", "File I/O"),
            new PgslSeedEntry("GameLoad", "GameLoad(slot)", "PGSL.GameLoad", "Load game state from a slot", "File I/O"),
            new PgslSeedEntry("GameSave", "GameSave(slot)", "PGSL.GameSave", "Save game state to a slot", "File I/O"),
            new PgslSeedEntry("Bool", "Bool(val) → bool", "PGSL.Bool", "Convert value to boolean", "General"),
            new PgslSeedEntry("GameEnd", "GameEnd()", "PGSL.GameEnd", "Ends the game", "General"),
            new PgslSeedEntry("Print", "Print(msg)", "PGSL.Print", "Print message to console", "General"),
            new PgslSeedEntry("Real", "Real(val) → float", "PGSL.Real", "Convert value to number", "General"),
            new PgslSeedEntry("ShowDebugMessage", "ShowDebugMessage(msg)", "PGSL.Print", "Alias for Print", "General"),
            new PgslSeedEntry("ShowMessage", "ShowMessage(msg)", "PGSL.ShowMessage", "Show dialog message", "General"),
            new PgslSeedEntry("String", "String(val) → string", "PGSL.PGSLToString", "Convert value to string", "General"),
            new PgslSeedEntry("PgGridAdd", "PgGridAdd(grid, x, y, z, val)", "PGSL.PgGridAdd", "Add to cell value", "Grids"),
            new PgslSeedEntry("PgGridContains", "PgGridContains(grid, x1, y1, x2, y2, val) → bool", "PGSL.PgGridContains", "Contains value", "Grids"),
            new PgslSeedEntry("PgGridCopy", "PgGridCopy(src, dst)", "PGSL.PgGridCopy", "Copy grid contents", "Grids"),
            new PgslSeedEntry("PgGridCreate", "PgGridCreate(w, h, d, wrapMode) → int", "PGSL.PgGridCreate", "Create a PG Grid", "Grids"),
            new PgslSeedEntry("PgGridFill", "PgGridFill(grid, val)", "PGSL.PgGridFill", "Fill grid", "Grids"),
            new PgslSeedEntry("PgGridFillCircle", "PgGridFillCircle(grid, cx, cy, r, val)", "PGSL.PgGridFillCircle", "Fill circle on 2D slice", "Grids"),
            new PgslSeedEntry("PgGridFillRegion", "PgGridFillRegion(grid, x1, y1, z1, x2, y2, z2, val)", "PGSL.PgGridFillRegion", "Fill region", "Grids"),
            new PgslSeedEntry("PgGridFindX", "PgGridFindX(grid, x1, y1, x2, y2, val) → int", "PGSL.PgGridFindX", "Find X of value", "Grids"),
            new PgslSeedEntry("PgGridFindY", "PgGridFindY(grid, x1, y1, x2, y2, val) → int", "PGSL.PgGridFindY", "Find Y of value", "Grids"),
            new PgslSeedEntry("PgGridForEach", "PgGridForEach(grid, scr)", "PGSL.PgGridForEach", "Run script for each cell", "Grids"),
            new PgslSeedEntry("PgGridGet", "PgGridGet(grid, x, y, z) → any", "PGSL.PgGridGet", "Get cell value", "Grids"),
            new PgslSeedEntry("PgGridHeight", "PgGridHeight(grid) → int", "PGSL.PgGridHeight", "Get grid height", "Grids"),
            new PgslSeedEntry("PgGridMax", "PgGridMax(grid, x1, y1, x2, y2) → float", "PGSL.PgGridMax", "Max in region", "Grids"),
            new PgslSeedEntry("PgGridMean", "PgGridMean(grid, x1, y1, x2, y2) → float", "PGSL.PgGridMean", "Mean in region", "Grids"),
            new PgslSeedEntry("PgGridMin", "PgGridMin(grid, x1, y1, x2, y2) → float", "PGSL.PgGridMin", "Min in region", "Grids"),
            new PgslSeedEntry("PgGridMul", "PgGridMul(grid, x, y, z, val)", "PGSL.PgGridMul", "Multiply cell value", "Grids"),
            new PgslSeedEntry("PgGridResize", "PgGridResize(grid, w, h)", "PGSL.PgGridResize", "Resize grid", "Grids"),
            new PgslSeedEntry("PgGridSet", "PgGridSet(grid, x, y, z, val)", "PGSL.PgGridSet", "Set cell value", "Grids"),
            new PgslSeedEntry("PgGridShuffle", "PgGridShuffle(grid)", "PGSL.PgGridShuffle", "Shuffle grid contents", "Grids"),
            new PgslSeedEntry("PgGridSortColumn", "PgGridSortColumn(grid, col, asc)", "PGSL.PgGridSortColumn", "Sort grid by column", "Grids"),
            new PgslSeedEntry("PgGridSum", "PgGridSum(grid, x1, y1, x2, y2) → float", "PGSL.PgGridSum", "Sum region", "Grids"),
            new PgslSeedEntry("PgGridWidth", "PgGridWidth(grid) → int", "PGSL.PgGridWidth", "Get grid width", "Grids"),
            new PgslSeedEntry("FileExists", "FileExists(path) → bool", "PGSL.FileExists", "Check if file exists", "IO"),
            new PgslSeedEntry("FileReadText", "FileReadText(path) → string", "PGSL.FileReadText", "Read string from file", "IO"),
            new PgslSeedEntry("FileWriteText", "FileWriteText(path, text)", "PGSL.FileWriteText", "Save string to file", "IO"),
            new PgslSeedEntry("KeyCheck", "KeyCheck(key) → bool", "PGSL.KeyCheck", "Check if key is held", "Input"),
            new PgslSeedEntry("KeyPressed", "KeyPressed(key) → bool", "PGSL.KeyPressed", "Check if key was pressed this frame", "Input"),
            new PgslSeedEntry("KeyReleased", "KeyReleased(key) → bool", "PGSL.KeyReleased", "Check if key was released this frame", "Input"),
            new PgslSeedEntry("MbLeft", "MbLeft → int", "PGSL.MbLeft", "MouseCheck flag for left button", "Input"),
            new PgslSeedEntry("MbMiddle", "MbMiddle → int", "PGSL.MbMiddle", "MouseCheck flag for middle button", "Input"),
            new PgslSeedEntry("MbRight", "MbRight → int", "PGSL.MbRight", "MouseCheck flag for right button", "Input"),
            new PgslSeedEntry("MouseCheck", "MouseCheck(button) → bool", "PGSL.MouseCheck", "Check if mouse button is held", "Input"),
            new PgslSeedEntry("MousePressed", "MousePressed(button) → bool", "PGSL.MousePressed", "Check if mouse button was pressed this frame", "Input"),
            new PgslSeedEntry("MouseReleased", "MouseReleased(button) → bool", "PGSL.MouseReleased", "Check if mouse button was released this frame", "Input"),
            new PgslSeedEntry("Depth", "Depth → int", "PGSL.Depth", "Rendering depth", "Instance Variables"),
            new PgslSeedEntry("Direction", "Direction → float", "PGSL.Direction", "Movement direction (degrees)", "Instance Variables"),
            new PgslSeedEntry("Friction", "Friction → float", "PGSL.Friction", "Deceleration per frame", "Instance Variables"),
            new PgslSeedEntry("Gravity", "Gravity → float", "PGSL.Gravity", "Gravity force", "Instance Variables"),
            new PgslSeedEntry("GravityDirection", "GravityDirection → float", "PGSL.GravityDirection", "Gravity direction (degrees)", "Instance Variables"),
            new PgslSeedEntry("HSpeed", "HSpeed → float", "PGSL.HSpeed", "Horizontal speed", "Instance Variables"),
            new PgslSeedEntry("ImageAlpha", "ImageAlpha → float", "PGSL.ImageAlpha", "Transparency (0-1)", "Instance Variables"),
            new PgslSeedEntry("ImageAngle", "ImageAngle → float", "PGSL.ImageAngle", "Rotation angle", "Instance Variables"),
            new PgslSeedEntry("ImageBlend", "ImageBlend → color", "PGSL.ImageBlend", "Color tint", "Instance Variables"),
            new PgslSeedEntry("ImageIndex", "ImageIndex → float", "PGSL.ImageIndex", "Current animation frame", "Instance Variables"),
            new PgslSeedEntry("ImageSpeed", "ImageSpeed → float", "PGSL.ImageSpeed", "Animation speed", "Instance Variables"),
            new PgslSeedEntry("ImageXScale", "ImageXScale → float", "PGSL.ImageXScale", "Horizontal scale", "Instance Variables"),
            new PgslSeedEntry("ImageYScale", "ImageYScale → float", "PGSL.ImageYScale", "Vertical scale", "Instance Variables"),
            new PgslSeedEntry("Solid", "Solid → bool", "PGSL.Solid", "Is object solid?", "Instance Variables"),
            new PgslSeedEntry("Speed", "Speed → float", "PGSL.Speed", "Movement speed", "Instance Variables"),
            new PgslSeedEntry("SpriteIndex", "SpriteIndex → string", "PGSL.SpriteIndex", "Sprite resource name", "Instance Variables"),
            new PgslSeedEntry("Visible", "Visible → bool", "PGSL.Visible", "Is object visible?", "Instance Variables"),
            new PgslSeedEntry("VSpeed", "VSpeed → float", "PGSL.VSpeed", "Vertical speed", "Instance Variables"),
            new PgslSeedEntry("X", "X → float", "PGSL.X", "Position X coordinate", "Instance Variables"),
            new PgslSeedEntry("Y", "Y → float", "PGSL.Y", "Position Y coordinate", "Instance Variables"),
            new PgslSeedEntry("Z", "Z → float", "PGSL.Z", "Position Z coordinate", "Instance Variables"),
            new PgslSeedEntry("CollisionCircle", "CollisionCircle(x, y, r, obj) → int", "PGSL.CollisionCircle", "Check for collision within a circle", "Instances"),
            new PgslSeedEntry("CollisionLine", "CollisionLine(x1, y1, x2, y2, obj) → int", "PGSL.CollisionLine", "Check if a line intersects an object", "Instances"),
            new PgslSeedEntry("CollisionRectangle", "CollisionRectangle(x1, y1, x2, y2, obj) → int", "PGSL.CollisionRectangle", "Check for collision within a rectangle", "Instances"),
            new PgslSeedEntry("CreateInstance", "CreateInstance(obj, x, y) → int", "PGSL.CreateInstance", "Create new instance", "Instances"),
            new PgslSeedEntry("InstanceCount", "InstanceCount(obj) → int", "PGSL.InstanceCount", "Count instances of a type", "Instances"),
            new PgslSeedEntry("InstanceDestroy", "InstanceDestroy(id)", "PGSL.InstanceDestroy", "Destroy instance", "Instances"),
            new PgslSeedEntry("InstanceExists", "InstanceExists(id) → bool", "PGSL.InstanceExists", "Check if instance exists", "Instances"),
            new PgslSeedEntry("InstanceNearest", "InstanceNearest(x, y, obj) → int", "PGSL.InstanceNearest", "Find nearest instance to point", "Instances"),
            new PgslSeedEntry("InstancePosition", "InstancePosition(x, y, obj) → int", "PGSL.InstancePosition", "Find instance at point", "Instances"),
            new PgslSeedEntry("PlaceMeeting", "PlaceMeeting(x, y, obj) → bool", "PGSL.PlaceMeeting", "Check collision at position", "Instances"),
            new PgslSeedEntry("PointMeeting", "PointMeeting(x, y, obj) → bool", "PGSL.PointMeeting", "Check if a point collides with an object", "Instances"),
            new PgslSeedEntry("JsonDecode", "JsonDecode(json) → any", "PGSL.JsonDecode", "Convert JSON string to object", "JSON"),
            new PgslSeedEntry("JsonEncode", "JsonEncode(obj) → string", "PGSL.JsonEncode", "Convert object to JSON string", "JSON"),
            new PgslSeedEntry("PgDecode", "PgDecode(jsonString) → int", "PGSL.PgDecode", "Decode JSON to structure", "JSON"),
            new PgslSeedEntry("PgEncode", "PgEncode(handle) → string", "PGSL.PgEncode", "Encode structure to JSON", "JSON"),
            new PgslSeedEntry("PgListAdd", "PgListAdd(list, val)", "PGSL.PgListAdd", "Add value to end of list", "Lists"),
            new PgslSeedEntry("PgListClear", "PgListClear(list)", "PGSL.PgListClear", "Clear list", "Lists"),
            new PgslSeedEntry("PgListCopy", "PgListCopy(src, dst)", "PGSL.PgListCopy", "Copy list contents", "Lists"),
            new PgslSeedEntry("PgListCreate", "PgListCreate([val1, val2, ...]) → int", "PGSL.PgListCreate", "Create a new PG List, optionally initialized with elements", "Lists"),
            new PgslSeedEntry("PgListDequeue", "PgListDequeue(list) → any", "PGSL.PgListDequeue", "Dequeue first item", "Lists"),
            new PgslSeedEntry("PgListFind", "PgListFind(list, val) → int", "PGSL.PgListFind", "Find index of value", "Lists"),
            new PgslSeedEntry("PgListForEach", "PgListForEach(list, scr)", "PGSL.PgListForEach", "Run script for each item", "Lists"),
            new PgslSeedEntry("PgListGet", "PgListGet(list, i) → any", "PGSL.PgListGet", "Get value at index", "Lists"),
            new PgslSeedEntry("PgListInsert", "PgListInsert(list, i, val)", "PGSL.PgListInsert", "Insert value at index", "Lists"),
            new PgslSeedEntry("PgListPop", "PgListPop(list) → any", "PGSL.PgListPop", "Pop last item", "Lists"),
            new PgslSeedEntry("PgListRemove", "PgListRemove(list, i)", "PGSL.PgListRemove", "Remove value at index", "Lists"),
            new PgslSeedEntry("PgListSet", "PgListSet(list, i, val)", "PGSL.PgListSet", "Set value at index", "Lists"),
            new PgslSeedEntry("PgListShuffle", "PgListShuffle(list)", "PGSL.PgListShuffle", "Shuffle list", "Lists"),
            new PgslSeedEntry("PgListSize", "PgListSize(list) → int", "PGSL.PgListSize", "Get list size", "Lists"),
            new PgslSeedEntry("PgListSort", "PgListSort(list, asc)", "PGSL.PgListSort", "Sort list", "Lists"),
            new PgslSeedEntry("PgMapClear", "PgMapClear(map)", "PGSL.PgMapClear", "Clear map", "Maps"),
            new PgslSeedEntry("PgMapCopy", "PgMapCopy(src, dst)", "PGSL.PgMapCopy", "Copy map contents", "Maps"),
            new PgslSeedEntry("PgMapCreate", "PgMapCreate() → int", "PGSL.PgMapCreate", "Create a new PG Map", "Maps"),
            new PgslSeedEntry("PgMapFirstKey", "PgMapFirstKey(map) → string", "PGSL.PgMapFirstKey", "Get first key", "Maps"),
            new PgslSeedEntry("PgMapForEach", "PgMapForEach(map, scr)", "PGSL.PgMapForEach", "Run script for each key-value pair", "Maps"),
            new PgslSeedEntry("PgMapGet", "PgMapGet(map, key) → any", "PGSL.PgMapGet", "Get map value", "Maps"),
            new PgslSeedEntry("PgMapHas", "PgMapHas(map, key) → bool", "PGSL.PgMapHas", "Check if key exists", "Maps"),
            new PgslSeedEntry("PgMapNextKey", "PgMapNextKey(map, key) → string", "PGSL.PgMapNextKey", "Get next key", "Maps"),
            new PgslSeedEntry("PgMapRemove", "PgMapRemove(map, key)", "PGSL.PgMapRemove", "Remove key", "Maps"),
            new PgslSeedEntry("PgMapSet", "PgMapSet(map, key, val)", "PGSL.PgMapSet", "Set map value", "Maps"),
            new PgslSeedEntry("PgMapSize", "PgMapSize(map) → int", "PGSL.PgMapSize", "Get map size", "Maps"),
            new PgslSeedEntry("Abs", "Abs(x) → float", "PGSL.Abs", "Absolute value", "Math"),
            new PgslSeedEntry("AngleDifference", "AngleDifference(a, b) → float", "PGSL.AngleDifference", "Signed difference between two angles", "Math"),
            new PgslSeedEntry("ArcCos", "ArcCos(x) → float", "PGSL.ArcCos", "Arc cosine", "Math"),
            new PgslSeedEntry("ArcSin", "ArcSin(x) → float", "PGSL.ArcSin", "Arc sine", "Math"),
            new PgslSeedEntry("ArcTan", "ArcTan(x) → float", "PGSL.ArcTan", "Arc tangent", "Math"),
            new PgslSeedEntry("ArcTan2", "ArcTan2(y, x) → float", "PGSL.ArcTan2", "Arc tangent of y/x", "Math"),
            new PgslSeedEntry("Ceil", "Ceil(x) → int", "PGSL.Ceil", "Round up to integer", "Math"),
            new PgslSeedEntry("Choose", "Choose(...args) → any", "PGSL.Choose", "Pick a random value from options", "Math"),
            new PgslSeedEntry("Clamp", "Clamp(v, min, max) → float", "PGSL.Clamp", "Clamp value to range", "Math"),
            new PgslSeedEntry("Cos", "Cos(x) → float", "PGSL.Cos", "Cosine (radians)", "Math"),
            new PgslSeedEntry("DegToRad", "DegToRad(d) → float", "PGSL.DegToRad", "Degrees to radians", "Math"),
            new PgslSeedEntry("E", "E → float", "PGSL.E", "Mathematical E", "Math"),
            new PgslSeedEntry("Exp", "Exp(x) → float", "PGSL.Exp", "Exponential", "Math"),
            new PgslSeedEntry("Floor", "Floor(x) → int", "PGSL.Floor", "Round down to integer", "Math"),
            new PgslSeedEntry("LengthDirX", "LengthDirX(len, dir) → float", "PGSL.LengthDirX", "X component of vector", "Math"),
            new PgslSeedEntry("LengthDirY", "LengthDirY(len, dir) → float", "PGSL.LengthDirY", "Y component of vector", "Math"),
            new PgslSeedEntry("LengthDirZ", "LengthDirZ(len, dir) → float", "PGSL.LengthDirZ", "Z component of vector on XZ ground plane", "Math"),
            new PgslSeedEntry("Lerp", "Lerp(a, b, t) → float", "PGSL.Lerp", "Linear interpolation", "Math"),
            new PgslSeedEntry("LerpAngle", "LerpAngle(from, to, t) → float", "PGSL.LerpAngle", "Interpolate between two angles", "Math"),
            new PgslSeedEntry("Log", "Log(x) → float", "PGSL.Log", "Natural logarithm", "Math"),
            new PgslSeedEntry("Log10", "Log10(x) → float", "PGSL.Log10", "Base-10 logarithm", "Math"),
            new PgslSeedEntry("Log2", "Log2(x) → float", "PGSL.Log2", "Base-2 logarithm", "Math"),
            new PgslSeedEntry("Max", "Max(a, b) → float", "PGSL.Max", "Maximum of two values", "Math"),
            new PgslSeedEntry("Min", "Min(a, b) → float", "PGSL.Min", "Minimum of two values", "Math"),
            new PgslSeedEntry("Mod", "Mod(a, b) → float", "PGSL.Mod", "Remainder of a divided by b (use instead of %)", "Math"),
            new PgslSeedEntry("MoveForward", "MoveForward(distance)", "PGSL.MoveForward", "Move instance forward along Direction on XZ plane", "Math"),
            new PgslSeedEntry("MoveForwardTileSafe", "MoveForwardTileSafe(distance)", "PGSL.MoveForwardTileSafe", "Move on XY plane with 2.5D elevation/stair rules", "Math"),
            new PgslSeedEntry("MoveInDirection", "MoveInDirection(speed)", "PGSL.MoveInDirection", "Move instance by Speed along Direction on XZ plane", "Math"),
            new PgslSeedEntry("Pi", "Pi → float", "PGSL.Pi", "Mathematical PI", "Math"),
            new PgslSeedEntry("PointDirection", "PointDirection(x1, y1, x2, y2) → float", "PGSL.PointDirection", "Angle from first point toward second (degrees)", "Math"),
            new PgslSeedEntry("PointDistance", "PointDistance(x1, y1, x2, y2) → float", "PGSL.PointDistance", "Distance between two points", "Math"),
            new PgslSeedEntry("Pow", "Pow(x, y) → float", "PGSL.Pow", "Power (x^y)", "Math"),
            new PgslSeedEntry("RadToDeg", "RadToDeg(r) → float", "PGSL.RadToDeg", "Radians to degrees", "Math"),
            new PgslSeedEntry("Random", "Random(n) → float", "PGSL.Random", "Random value from 0 to n", "Math"),
            new PgslSeedEntry("RandomFloat", "RandomFloat() → float", "PGSL.RandomFloat", "Random value between 0 and 1", "Math"),
            new PgslSeedEntry("RandomRange", "RandomRange(min, max) → float", "PGSL.RandomRange", "Random value in range", "Math"),
            new PgslSeedEntry("Round", "Round(x) → int", "PGSL.Round", "Round to nearest integer", "Math"),
            new PgslSeedEntry("Sign", "Sign(x) → float", "PGSL.Sign", "Sign of value (-1, 0, 1)", "Math"),
            new PgslSeedEntry("Sin", "Sin(x) → float", "PGSL.Sin", "Sine (radians)", "Math"),
            new PgslSeedEntry("Sqrt", "Sqrt(x) → float", "PGSL.Sqrt", "Square root", "Math"),
            new PgslSeedEntry("Tan", "Tan(x) → float", "PGSL.Tan", "Tangent (radians)", "Math"),
            new PgslSeedEntry("ParticleBurst", "ParticleBurst(psys, x, y, count)", "PGSL.ParticleBurst", "Emit particles", "Particles"),
            new PgslSeedEntry("ParticleSystemCreate", "ParticleSystemCreate(preset) → int", "PGSL.ParticleSystemCreate", "Create particle system from preset name", "Particles"),
            new PgslSeedEntry("ParticleSystemDestroy", "ParticleSystemDestroy(id)", "PGSL.ParticleSystemDestroy", "Destroy particle system", "Particles"),
            new PgslSeedEntry("Path2DRequest", "Path2DRequest(x1, y1, x2, y2) → int", "PGSL.Path2DRequest", "Start async 2D pathfind; returns path handle", "Pathfinding"),
            new PgslSeedEntry("PathCreateNavMesh", "PathCreateNavMesh(gridHandle, cellSize, is3D) → bool", "PGSL.PathCreateNavMesh", "Build navmesh from a PgGrid (0/false = walkable)", "Pathfinding"),
            new PgslSeedEntry("PathFree", "PathFree(handle)", "PGSL.PathFree", "Release a path handle", "Pathfinding"),
            new PgslSeedEntry("PathGetLength", "PathGetLength(handle) → float", "PGSL.PathGetLength", "Total path length in world units", "Pathfinding"),
            new PgslSeedEntry("PathGetNextDirection", "PathGetNextDirection(handle, x, y, z) → float", "PGSL.PathGetNextDirection", "Direction toward next waypoint (degrees)", "Pathfinding"),
            new PgslSeedEntry("PathGetPoint", "PathGetPoint(handle, index) → any", "PGSL.PathGetPoint", "Waypoint x,y,z as array", "Pathfinding"),
            new PgslSeedEntry("PathGetPointCount", "PathGetPointCount(handle) → int", "PGSL.PathGetPointCount", "Number of waypoints in path", "Pathfinding"),
            new PgslSeedEntry("PathReady", "PathReady(handle) → bool", "PGSL.PathReady", "True when path computation finished", "Pathfinding"),
            new PgslSeedEntry("PathRequest", "PathRequest(x1, y1, z1, x2, y2, z2) → int", "PGSL.PathRequest", "Start async pathfind; returns path handle", "Pathfinding"),
            new PgslSeedEntry("RoomExists", "RoomExists(name) → bool", "PGSL.RoomExists", "True if room JSON exists in the project", "Rooms"),
            new PgslSeedEntry("RoomGetHeight", "RoomGetHeight(x, y) → int", "PGSL.RoomGetHeight", "Elevation at pixel position (0-15)", "Rooms"),
            new PgslSeedEntry("RoomGetName", "RoomGetName() → string", "PGSL.RoomGetName", "Get the name of the current room", "Rooms"),
            new PgslSeedEntry("RoomIsTransitioning", "RoomIsTransitioning() → bool", "PGSL.RoomIsTransitioning", "True while a room fade transition is active", "Rooms"),
            new PgslSeedEntry("RoomRestart", "RoomRestart()", "PGSL.RoomRestart", "Restart current room", "Rooms"),
            new PgslSeedEntry("RoomTileFree", "RoomTileFree(x, y) → bool", "PGSL.RoomTileFree", "True if tile at position is walkable at current floor height", "Rooms"),
            new PgslSeedEntry("RoomTransition", "RoomTransition(room, type, duration)", "PGSL.RoomTransition", "Switch room with a transition effect", "Rooms"),
            new PgslSeedEntry("RoomTransitionGetName", "RoomTransitionGetName() → string", "PGSL.RoomTransitionGetName", "Current transition effect (canonical name)", "Rooms"),
            new PgslSeedEntry("RoomTransitionIsValid", "RoomTransitionIsValid(name) → bool", "PGSL.RoomTransitionIsValid", "True if name is a built-in transition effect", "Rooms"),
            new PgslSeedEntry("RoomTransitionNames", "RoomTransitionNames() → string", "PGSL.RoomTransitionNames", "Comma-separated list of built-in transition effect names", "Rooms"),
            new PgslSeedEntry("DrawSpriteAnimation", "DrawSpriteAnimation(tagName, x, y)", "PGSL.DrawSpriteAnimation", "Draw current frame of a sprite animation tag", "Sprites"),
            new PgslSeedEntry("SpriteAnimationExists", "SpriteAnimationExists(spriteName, tagName) → bool", "PGSL.SpriteAnimationExists", "Check if a sprite has the named animation tag", "Sprites"),
            new PgslSeedEntry("SpriteGetAnimationFrameCount", "SpriteGetAnimationFrameCount(tagName) → int", "PGSL.SpriteGetAnimationFrameCount", "Frame count in the animation tag on current sprite", "Sprites"),
            new PgslSeedEntry("SpritePlayAnimation", "SpritePlayAnimation(tagName, speed, loop)", "PGSL.SpritePlayAnimation", "Play sprite frames from an animation tag", "Sprites"),
            new PgslSeedEntry("SpriteSetAnimation", "SpriteSetAnimation(tagName)", "PGSL.SpriteSetAnimation", "Set current animation tag without restarting playback", "Sprites"),
            new PgslSeedEntry("SpriteStopAnimation", "SpriteStopAnimation()", "PGSL.SpriteStopAnimation", "Stop tag-based sprite animation", "Sprites"),
            new PgslSeedEntry("StringLength", "StringLength(str) → int", "PGSL.StringLength", "Get character count", "Strings"),
            new PgslSeedEntry("StringLower", "StringLower(str) → string", "PGSL.StringLower", "Convert to lowercase", "Strings"),
            new PgslSeedEntry("StringPos", "StringPos(substr, str) → int", "PGSL.StringPos", "Find index of substring", "Strings"),
            new PgslSeedEntry("StringReplace", "StringReplace(str, old, new) → string", "PGSL.StringReplace", "Replace all occurrences", "Strings"),
            new PgslSeedEntry("StringSplit", "StringSplit(str, sep) → any", "PGSL.StringSplit", "Split string into a list", "Strings"),
            new PgslSeedEntry("StringSubstring", "StringSubstring(str, start, len) → string", "PGSL.StringSubstring", "Extract portion of string", "Strings"),
            new PgslSeedEntry("StringTrim", "StringTrim(str) → string", "PGSL.StringTrim", "Remove whitespace from ends", "Strings"),
            new PgslSeedEntry("StringUpper", "StringUpper(str) → string", "PGSL.StringUpper", "Convert to uppercase", "Strings"),
            new PgslSeedEntry("DisplayGetHeight", "DisplayGetHeight() → int", "PGSL.DisplayGetHeight", "Get screen height", "System"),
            new PgslSeedEntry("DisplayGetWidth", "DisplayGetWidth() → int", "PGSL.DisplayGetWidth", "Get screen width", "System"),
            new PgslSeedEntry("OsType", "OsType → string", "PGSL.OsType", "Get operating system", "System"),
            new PgslSeedEntry("RoomGoto", "RoomGoto(name)", "PGSL.RoomGoto", "Switch to a different room", "System"),
            new PgslSeedEntry("RoomGoTo", "RoomGoTo(name, [trans], [dur])", "PGSL.RoomGoTo", "Transition to a different room", "System"),
            new PgslSeedEntry("RoomGoToNext", "RoomGoToNext()", "PGSL.RoomGoToNext", "Go to the next room in order", "System"),
            new PgslSeedEntry("RoomGoToPrevious", "RoomGoToPrevious()", "PGSL.RoomGoToPrevious", "Go to the previous room in order", "System"),
            new PgslSeedEntry("CurrentDay", "CurrentDay → int", "PGSL.CurrentDay", "Current day of month (1-31)", "Time & Date"),
            new PgslSeedEntry("CurrentHour", "CurrentHour → int", "PGSL.CurrentHour", "Current hour (0-23)", "Time & Date"),
            new PgslSeedEntry("CurrentMilliseconds", "CurrentMilliseconds → int", "PGSL.CurrentMilliseconds", "Current Unix timestamp in ms", "Time & Date"),
            new PgslSeedEntry("CurrentMinute", "CurrentMinute → int", "PGSL.CurrentMinute", "Current minute (0-59)", "Time & Date"),
            new PgslSeedEntry("CurrentMonth", "CurrentMonth → int", "PGSL.CurrentMonth", "Current month (1-12)", "Time & Date"),
            new PgslSeedEntry("CurrentSecond", "CurrentSecond → int", "PGSL.CurrentSecond", "Current second (0-59)", "Time & Date"),
            new PgslSeedEntry("CurrentYear", "CurrentYear → int", "PGSL.CurrentYear", "Current year", "Time & Date"),
            new PgslSeedEntry("DateString", "DateString(fmt) → string", "PGSL.DateString", "Current date as formatted string", "Time & Date"),
            new PgslSeedEntry("TimeString", "TimeString(fmt) → string", "PGSL.TimeString", "Current time as formatted string", "Time & Date"),
            new PgslSeedEntry("UserDefined0", "UserDefined0 → float", "PGSL.UserDefined0", "User variable 0", "User Variables"),
            new PgslSeedEntry("UserDefined1", "UserDefined1 → float", "PGSL.UserDefined1", "User variable 1", "User Variables"),
            new PgslSeedEntry("UserDefined10", "UserDefined10 → float", "PGSL.UserDefined10", "User variable 10", "User Variables"),
            new PgslSeedEntry("UserDefined11", "UserDefined11 → float", "PGSL.UserDefined11", "User variable 11", "User Variables"),
            new PgslSeedEntry("UserDefined2", "UserDefined2 → float", "PGSL.UserDefined2", "User variable 2", "User Variables"),
            new PgslSeedEntry("UserDefined3", "UserDefined3 → float", "PGSL.UserDefined3", "User variable 3", "User Variables"),
            new PgslSeedEntry("UserDefined4", "UserDefined4 → float", "PGSL.UserDefined4", "User variable 4", "User Variables"),
            new PgslSeedEntry("UserDefined5", "UserDefined5 → float", "PGSL.UserDefined5", "User variable 5", "User Variables"),
            new PgslSeedEntry("UserDefined6", "UserDefined6 → float", "PGSL.UserDefined6", "User variable 6", "User Variables"),
            new PgslSeedEntry("UserDefined7", "UserDefined7 → float", "PGSL.UserDefined7", "User variable 7", "User Variables"),
            new PgslSeedEntry("UserDefined8", "UserDefined8 → float", "PGSL.UserDefined8", "User variable 8", "User Variables"),
            new PgslSeedEntry("UserDefined9", "UserDefined9 → float", "PGSL.UserDefined9", "User variable 9", "User Variables"),
            new PgslSeedEntry("CameraMoveForward", "CameraMoveForward(distance)", "PGSL.CameraMoveForward", "Move active view forward along its yaw", "Views"),
            new PgslSeedEntry("CameraMoveRight", "CameraMoveRight(distance)", "PGSL.CameraMoveRight", "Move active view right (strafe)", "Views"),
            new PgslSeedEntry("CameraMoveUp", "CameraMoveUp(distance)", "PGSL.CameraMoveUp", "Move active view up (world Y)", "Views"),
            new PgslSeedEntry("ViewGet", "ViewGet(view, property) → float", "PGSL.ViewGet", "Get a numeric view property by name", "Views"),
            new PgslSeedEntry("ViewGetActive", "ViewGetActive() → float", "PGSL.ViewGetActive", "Currently active view index", "Views"),
            new PgslSeedEntry("ViewGetBoundsH", "ViewGetBoundsH(view) → float", "PGSL.ViewGetBoundsH", "Visible world height", "Views"),
            new PgslSeedEntry("ViewGetBoundsW", "ViewGetBoundsW(view) → float", "PGSL.ViewGetBoundsW", "Visible world width", "Views"),
            new PgslSeedEntry("ViewGetCount", "ViewGetCount() → float", "PGSL.ViewGetCount", "Number of views defined for the current room", "Views"),
            new PgslSeedEntry("ViewGetEnabled", "ViewGetEnabled(view) → float", "PGSL.ViewGetEnabled", "Returns 1 if view is enabled", "Views"),
            new PgslSeedEntry("ViewGetFollow", "ViewGetFollow(view) → string", "PGSL.ViewGetFollow", "Name of object the view follows", "Views"),
            new PgslSeedEntry("ViewGetFollowBorderH", "ViewGetFollowBorderH(view) → float", "PGSL.ViewGetFollowBorderH", "Horizontal follow border", "Views"),
            new PgslSeedEntry("ViewGetFollowBorderV", "ViewGetFollowBorderV(view) → float", "PGSL.ViewGetFollowBorderV", "Vertical follow border", "Views"),
            new PgslSeedEntry("ViewGetFollowSpeedH", "ViewGetFollowSpeedH(view) → float", "PGSL.ViewGetFollowSpeedH", "Horizontal follow speed", "Views"),
            new PgslSeedEntry("ViewGetFollowSpeedV", "ViewGetFollowSpeedV(view) → float", "PGSL.ViewGetFollowSpeedV", "Vertical follow speed", "Views"),
            new PgslSeedEntry("ViewGetFov", "ViewGetFov(view) → float", "PGSL.ViewGetFov", "Perspective FOV in degrees (3D)", "Views"),
            new PgslSeedEntry("ViewGetPitch", "ViewGetPitch(view) → float", "PGSL.ViewGetPitch", "First-person pitch in degrees", "Views"),
            new PgslSeedEntry("ViewGetPosX", "ViewGetPosX(view) → float", "PGSL.ViewGetPosX", "View camera X", "Views"),
            new PgslSeedEntry("ViewGetPosY", "ViewGetPosY(view) → float", "PGSL.ViewGetPosY", "View camera Y", "Views"),
            new PgslSeedEntry("ViewGetPosZ", "ViewGetPosZ(view) → float", "PGSL.ViewGetPosZ", "View camera Z (3D floor depth)", "Views"),
            new PgslSeedEntry("ViewGetViewportH", "ViewGetViewportH(view) → float", "PGSL.ViewGetViewportH", "Viewport height", "Views"),
            new PgslSeedEntry("ViewGetViewportW", "ViewGetViewportW(view) → float", "PGSL.ViewGetViewportW", "Viewport width", "Views"),
            new PgslSeedEntry("ViewGetViewportX", "ViewGetViewportX(view) → float", "PGSL.ViewGetViewportX", "Viewport left edge", "Views"),
            new PgslSeedEntry("ViewGetViewportY", "ViewGetViewportY(view) → float", "PGSL.ViewGetViewportY", "Viewport top edge", "Views"),
            new PgslSeedEntry("ViewGetYaw", "ViewGetYaw(view) → float", "PGSL.ViewGetYaw", "First-person yaw in degrees", "Views"),
            new PgslSeedEntry("ViewMoveForward", "ViewMoveForward(view, distance)", "PGSL.ViewMoveForward", "Move view eye forward along view yaw (XZ)", "Views"),
            new PgslSeedEntry("ViewMoveRight", "ViewMoveRight(view, distance)", "PGSL.ViewMoveRight", "Move view eye right (strafe)", "Views"),
            new PgslSeedEntry("ViewMoveUp", "ViewMoveUp(view, distance)", "PGSL.ViewMoveUp", "Move view eye up (world Y)", "Views"),
            new PgslSeedEntry("ViewReset", "ViewReset(view)", "PGSL.ViewReset", "Restore view settings from room defaults", "Views"),
            new PgslSeedEntry("ViewSet", "ViewSet(view, property, value)", "PGSL.ViewSet", "Set a view property by name (PosX, BoundsW, Follow, etc.)", "Views"),
            new PgslSeedEntry("ViewSetActive", "ViewSetActive(view)", "PGSL.ViewSetActive", "Set which view index drives the camera", "Views"),
            new PgslSeedEntry("ViewSetBounds", "ViewSetBounds(view, width, height)", "PGSL.ViewSetBounds", "Visible world width and height for the view", "Views"),
            new PgslSeedEntry("ViewSetBoundsH", "ViewSetBoundsH(view, height)", "PGSL.ViewSetBoundsH", "Visible world height for the view", "Views"),
            new PgslSeedEntry("ViewSetBoundsW", "ViewSetBoundsW(view, width)", "PGSL.ViewSetBoundsW", "Visible world width for the view", "Views"),
            new PgslSeedEntry("ViewSetEnabled", "ViewSetEnabled(view, enabled)", "PGSL.ViewSetEnabled", "Enable or disable a view", "Views"),
            new PgslSeedEntry("ViewSetFollow", "ViewSetFollow(view, objectName)", "PGSL.ViewSetFollow", "Object to follow (empty string to disable)", "Views"),
            new PgslSeedEntry("ViewSetFollowBorder", "ViewSetFollowBorder(view, h, v)", "PGSL.ViewSetFollowBorder", "Follow dead-zone borders (world units)", "Views"),
            new PgslSeedEntry("ViewSetFollowSpeed", "ViewSetFollowSpeed(view, hSpd, vSpd)", "PGSL.ViewSetFollowSpeed", "Follow speed (-1 = instant snap)", "Views"),
            new PgslSeedEntry("ViewSetFov", "ViewSetFov(view, degrees)", "PGSL.ViewSetFov", "Perspective field of view for 3D rooms", "Views"),
            new PgslSeedEntry("ViewSetFrustumNear", "ViewSetFrustumNear(view, distance)", "PGSL.ViewSetFrustumNear", "Near clipping plane for 3D rooms", "Views"),
            new PgslSeedEntry("ViewSetFrustumFar", "ViewSetFrustumFar(view, distance)", "PGSL.ViewSetFrustumFar", "Far clipping plane for 3D rooms", "Views"),
            new PgslSeedEntry("ViewGetFrustumNear", "ViewGetFrustumNear(view)", "PGSL.ViewGetFrustumNear", "Get near clipping plane", "Views"),
            new PgslSeedEntry("ViewGetFrustumFar", "ViewGetFrustumFar(view)", "PGSL.ViewGetFrustumFar", "Get far clipping plane", "Views"),
            new PgslSeedEntry("ViewSetPitch", "ViewSetPitch(view, degrees)", "PGSL.ViewSetPitch", "First-person pitch in degrees (3D play)", "Views"),
            new PgslSeedEntry("ViewSetPosX", "ViewSetPosX(view, x)", "PGSL.ViewSetPosX", "Set view camera X (horizontal)", "Views"),
            new PgslSeedEntry("ViewSetPosY", "ViewSetPosY(view, y)", "PGSL.ViewSetPosY", "Set view camera Y (2D: screen vertical; 3D: height up)", "Views"),
            new PgslSeedEntry("ViewSetPosZ", "ViewSetPosZ(view, z)", "PGSL.ViewSetPosZ", "Set view camera Z (3D floor depth; ignored in 2D)", "Views"),
            new PgslSeedEntry("ViewSetViewport", "ViewSetViewport(view, x, y, w, h)", "PGSL.ViewSetViewport", "Screen rectangle where the view is drawn (pixels)", "Views"),
            new PgslSeedEntry("ViewSetViewportH", "ViewSetViewportH(view, h)", "PGSL.ViewSetViewportH", "Viewport height in pixels", "Views"),
            new PgslSeedEntry("ViewSetViewportW", "ViewSetViewportW(view, w)", "PGSL.ViewSetViewportW", "Viewport width in pixels", "Views"),
            new PgslSeedEntry("ViewSetViewportX", "ViewSetViewportX(view, x)", "PGSL.ViewSetViewportX", "Viewport left edge in pixels", "Views"),
            new PgslSeedEntry("ViewSetViewportY", "ViewSetViewportY(view, y)", "PGSL.ViewSetViewportY", "Viewport top edge in pixels", "Views"),
            new PgslSeedEntry("ViewSetYaw", "ViewSetYaw(view, degrees)", "PGSL.ViewSetYaw", "First-person yaw on XZ plane (3D play)", "Views"),

            // Physics body tags — proposed declarative syntax for attaching a rigid body to an object
            // without per-tweak engine code. Tracked in their own "Physics" tab (see
            // PgslCommandRegistry.GetPhysicsCatalog), not the general PGSL tab, mirroring how Engine.*
            // commands get their own Engine tab. None of these are wired into a live parser yet, so
            // IsImplemented reports false for all of them until a PgslCommandAttribute-tagged member
            // exists for each name — same automatic mechanism the rest of this catalogue uses.
            new PgslSeedEntry("Physics", "Physics = <PresetName>", "Genesis.Physics.BodyTags.Physics", "Selects a named physics preset/profile for this object, e.g. \"Physics = Default\" for the engine's built-in rigid-body preset", "Physics"),
            new PgslSeedEntry("BodyType", "BodyType = RigidBody | Kinematic | Static | Trigger", "Genesis.Physics.BodyTags.BodyType", "How the body is simulated: RigidBody (full dynamics), Kinematic (script-driven, pushes others), Static (immovable), Trigger (collision events only, no response)", "Physics"),
            new PgslSeedEntry("BodyShape", "BodyShape = Cube | Cylinder | Sphere | Capsule", "Genesis.Physics.BodyTags.BodyShape", "Collision shape used for this body's bounding volume", "Physics"),
            new PgslSeedEntry("BodyLength", "BodyLength = <units>", "Genesis.Physics.BodyTags.BodyLength", "Body extent along Z (depth), e.g. \"BodyLength = BlockSize*2\"", "Physics"),
            new PgslSeedEntry("BodyWidth", "BodyWidth = <units>", "Genesis.Physics.BodyTags.BodyWidth", "Body extent along X (width), e.g. \"BodyWidth = BlockSize*2\"", "Physics"),
            new PgslSeedEntry("BodyHeight", "BodyHeight = <units>", "Genesis.Physics.BodyTags.BodyHeight", "Body extent along Y (height), e.g. \"BodyHeight = BlockSize*2\"", "Physics"),
            new PgslSeedEntry("BodyOrigin", "BodyOrigin = CentrePoint | BottomPoint | TopPoint | LeftPoint | RightPoint | TopLeft | TopRight | BottomLeft | BottomRight | (x, y, z)", "Genesis.Physics.BodyTags.BodyOrigin", "Which point of the body's bounds maps to the object's world position — a named anchor preset, or a raw (x, y, z) offset for full control", "Physics"),
        };
    }

    /// <summary>One row of the full legacy PGSL command seed table.</summary>
    public readonly struct PgslSeedEntry
    {
        public readonly string Name;
        public readonly string Signature;
        public readonly string CSharpMap;
        public readonly string Description;
        public readonly string Category;

        public PgslSeedEntry(string name, string signature, string csharpMap, string description, string category)
        {
            Name = name;
            Signature = signature;
            CSharpMap = csharpMap;
            Description = description;
            Category = category;
        }
    }
}
